### ISSUE TITLE
Issue with meta 

### ISSUE THREAD

**Issue by gigabit101** [al132/Packet-Filter#1]
So there is a issue making a ItemStack with meta/nbt not unique so eg polished stone and stone are the same thing.

ItemStack.areItemsEqual can be real derpy sometimes.

I give you full permissions to reuse any of the code I link bellow in this mod.
https://github.com/TechReborn/RebornCore/blob/1.10.2/src/main/java/reborncore/common/util/ItemUtils.java#L37

**Comment by al132** [comment]
I already uploaded a fixed version to curse before I saw your issue. Thanks anyway!

**Comment by al132** [comment]
I realized I didn't take care of NBT data. I'll do that when I get a chance

**Comment by al132** [comment]
I have now added NBT and meta filtering, as well as toggle buttons for both.
