### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by PetersonE1** [al132/Packet-Filter#2]
I placed down a Routing Item Splitter and put an item inside.  It gets sent to a side, but when I take it out, it put another one back in, infinitely.  Shift-Clicking breaks the loop.

packet filter 1.4.0
forge-13.20.0.2227
minecraft 1.11.2

**Comment by PetersonE1** [comment]
https://drive.google.com/open?id=0Bz-b0WmaI8X2VVR2S1hTUWlTZGc

This is a video showing the bug.

**Comment by al132** [comment]
Thanks for letting me know. Hopefully I can get this fixed right away.

**Comment by al132** [comment]
I can't seem to replicate this bug on my own, even after updating forge and CompatLayer to newer versions. Could you give me more information, like what pack/modlist you're playing?

**Comment by dannydjdk** [comment]
It's not SpongeForge. He's playing on my forge server with a private pack which is similar to the ATM2 pack with a few different mods: http://dannyandson.com/unreal-tech-modpack/

We are able to replicate the problem reliably on our server. Some users have reported that it only happens for them immediately after placing the block.

We're also running a couple server side mods including Thuts Essentials, ThutPerms and Simple Protection. I'd be very surprised if they have any impact, but stranger things have happened.

**Comment by al132** [comment]
Can you duplicate this behavior with the pack while in single player?

**Comment by PetersonE1** [comment]
I launched a singleplayer testing world and was able to duplicate items using the routing item splitter.

**Comment by al132** [comment]
I seemed to have figured it out. I released a new version - 1.5.0 https://minecraft.curseforge.com/projects/packet-filter/files/2382508


Thank you for reporting the bug
